#!/bin/zsh
# Drop Cargo's target/ cache when it exceeds a size budget.
# Default budget: 8 GiB (one release build alone is often ~5 GiB).
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd -P)"
max_gb=8
force=false
dry_run=false

usage() {
    cat <<'EOF'
Usage: scripts/prune-target.zsh [options]

If target/ is larger than the budget (default 8 GiB), remove it entirely.
Safe: target/ is regenerated by the next cargo / release build.

Options:
  --max-gb N     size budget in GiB (default: 8)
  --force        remove target/ even when under budget
  --dry-run      print size / decision only; do not delete
  -h, --help     show this help
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --max-gb)
            [[ $# -ge 2 ]] || { print -u2 "prune-target: --max-gb requires a number"; exit 1; }
            max_gb="$2"
            shift 2
            ;;
        --force)
            force=true
            shift
            ;;
        --dry-run)
            dry_run=true
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            print -u2 "prune-target: unknown option: $1"
            usage >&2
            exit 1
            ;;
    esac
done

if ! [[ "$max_gb" == <-> ]] || (( max_gb < 1 )); then
    print -u2 "prune-target: --max-gb must be an integer >= 1 (got: $max_gb)"
    exit 1
fi

target_dir="$repo_root/target"
if [[ ! -d "$target_dir" ]]; then
    print "prune-target: no target/ at $repo_root — nothing to do"
    exit 0
fi

# du -sk reports 1024-byte blocks on macOS/BSD.
size_kb="$(du -sk "$target_dir" | awk '{print $1}')"
max_kb=$(( max_gb * 1024 * 1024 ))
# One decimal place for humans (awk avoids bc dependency).
size_gb="$(awk -v kb="$size_kb" 'BEGIN { printf "%.1f", kb / (1024 * 1024) }')"

print "prune-target: target/ is ${size_gb} GiB (budget ${max_gb} GiB)"

if [[ "$force" != true ]] && (( size_kb <= max_kb )); then
    print "prune-target: under budget — keeping target/"
    exit 0
fi

if [[ "$force" == true ]]; then
    print "prune-target: --force — removing target/"
else
    print "prune-target: over budget — removing target/"
fi

if [[ "$dry_run" == true ]]; then
    print "prune-target: dry-run — would delete $target_dir"
    exit 0
fi

rm -rf "$target_dir"
print "prune-target: removed $target_dir"
